In [ ]:
# LAB EXERCISE: MATRIX BACKPROPAGATION (3 -> 3 -> 1)

import numpy as np
# Input (1x3) and Target (1x1)
X = np.array([[2.0, 1.0, 3.0]])
y = np.array([[4.0]])

# Learning Rate
lr = 0.05

# Initial Weights
# W1 is 3x3 (3 inputs connected to 3 hidden nodes)
W1 = np.array([[ 0.5, -0.1,  0.2],
               [ 0.1,  0.3, -0.4],
               [ 0.2,  0.4,  0.1]])

# W2 is 3x1 (3 hidden nodes connected to 1 output node)
W2 = np.array([[ 1.0],
               [ 0.5],
               [-1.0]])

print("--- INITIAL WEIGHTS ---")
print("W1 (3x3):\n", W1)
print("W2 (3x1):\n", W2, "\n")

# Helper functions for ReLU
def relu(z):
    return np.maximum(0, z)

def relu_derivative(z):
    return (z > 0).astype(float)


# STEP 1: THE FORWARD PASS

Z1 = np.dot(X, W1)
H1 = relu(Z1)
y_pred = np.dot(H1, W2)

print("--- FORWARD PASS ---")
print(f"Prediction: {y_pred[0][0]:.4f} (Target is {y[0][0]})\n")


# STEP 2: THE LOSS
dy_pred = y_pred - y
loss = 0.5 * np.sum(dy_pred ** 2)

print("--- LOSS CALCULATION ---")
print(f"Raw Error: {dy_pred[0][0]:.4f}")
print(f"MSE Loss: {loss:.4f}\n")


# STEP 3: BACKPROPAGATION (THE GRADIENTS)
dW2 = np.dot(H1.T, dy_pred)
dH1 = np.dot(dy_pred, W2.T)
dZ1 = dH1 * relu_derivative(Z1)
dW1 = np.dot(X.T, dZ1)

print("--- CALCULATED GRADIENTS ---")
print("dW1 (3x3):\n", dW1)
print("dW2 (3x1):\n", dW2, "\n")


# STEP 4: GRADIENT DESCENT (WEIGHT UPDATE)
W1_new = W1 - lr * dW1
W2_new = W2 - lr * dW2

print("--- UPDATED WEIGHTS ---")
print("New W1:\n", np.round(W1_new, 4))
print("New W2:\n", np.round(W2_new, 4), "\n")


# Final Check
new_Z1 = np.dot(X, W1_new)
new_H1 = relu(new_Z1)
new_prediction = np.dot(new_H1, W2_new)

print("--- FINAL RESULT ---")
print(f"Old Prediction: {y_pred[0][0]:.4f}")
print(f"New Prediction: {new_prediction[0][0]:.4f}")
print("If successful, the new prediction should be closer to 4.0!")

--- INITIAL WEIGHTS ---
W1 (3x3):
 [[ 0.5 -0.1  0.2]
 [ 0.1  0.3 -0.4]
 [ 0.2  0.4  0.1]]
W2 (3x1):
 [[ 1. ]
 [ 0.5]
 [-1. ]] 

--- FORWARD PASS ---
Prediction: 2.0500 (Target is 4.0)

--- LOSS CALCULATION ---
Raw Error: -1.9500
MSE Loss: 1.9012

--- CALCULATED GRADIENTS ---
dW1 (3x3):
 [[-3.9   -1.95   3.9  ]
 [-1.95  -0.975  1.95 ]
 [-5.85  -2.925  5.85 ]]
dW2 (3x1):
 [[-3.315]
 [-2.535]
 [-0.585]] 

--- UPDATED WEIGHTS ---
New W1:
 [[ 0.695  -0.0025  0.005 ]
 [ 0.1975  0.3488 -0.4975]
 [ 0.4925  0.5462 -0.1925]]
New W2:
 [[ 1.1658]
 [ 0.6268]
 [-0.9708]] 

--- FINAL RESULT ---
Old Prediction: 2.0500
New Prediction: 4.8156
If successful, the new prediction should be closer to 4.0!
